In [1]:
# Q-Table Learning
import gym
import numpy as np

In [2]:
# Load the environment
env = gym.make('FrozenLake-v0')

[2017-08-21 20:01:54,918] Making new env: FrozenLake-v0


In [8]:
env.observation_space.to_jsonable

<bound method Space.to_jsonable of Discrete(16)>

In [67]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 5000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 500:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a_space = Q[s,:]
        a = np.random.choice(np.argwhere(a_space == np.max(a_space)).flatten())
        #a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        if r == 1:
            print(Q[s,a])
        #if s1 in [5,7,11,12]:
        #    r -= .1
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        if r == 1:
            print(Q[s,a])
        #Q[s,a] = r + y * np.max(Q[s1,:])
        #Q[s,a] = Q[s,a] + (r +(y*np.max(Q[s1,:]) - Q[s,a]))
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

0.0
0.8
0.147456
0.8294912
0.8294912
0.96589824
0.96589824
0.993179648
0.581937116726
0.916387423345
0.879731926411
0.975946385282
0.608202838652
0.92164056773
0.92164056773
0.984328113546
0.689953682853
0.937990736571
0.33082950758
0.866165901516
0.171900868856
0.834380173771
0.663282252963
0.932656450593
0.859536184866
0.971907236973
0.19039482095
0.83807896419
0.83807896419
0.967615792838
0.967615792838
0.993523158568
0.993523158568
0.998704631714
0.890129146389
0.978025829278
0.710851140044
0.942170228009
0.942170228009
0.988434045602
0.988434045602
0.99768680912
0.99768680912
0.999537361824
0.999537361824
0.999907472365
0.458070134509
0.891614026902
0.891614026902
0.97832280538
0.229569078676
0.845913815735
0.779594172582
0.955918834516
0.955918834516
0.991183766903
0.991183766903
0.998236753381
0.752554147544
0.950510829509
0.287533094765
0.857506618953
0.857506618953
0.971501323791
0.895335620005
0.979067124001
0.979067124001
0.9958134248
0.9958134248
0.99916268496
0.92082833045

0.807184172254
0.961436834451
0.163371038766
0.832674207753
0.64846563485
0.92969312697
0.525081708166
0.905016341633
0.295887811322
0.859177562264
0.859177562264
0.971835512453
0.000526014915747
0.800105202983
0.0450935428496
0.80901870857
0.80901870857
0.961803741714
0.150635684076
0.830127136815
0.0365228790226
0.807304575805
0.60878136751
0.921756273502
0.921756273502
0.9843512547
0.374442109277
0.874888421855
0.167978173522
0.833595634704
0.215009642585
0.843001928517
0.809281851376
0.961856370275
0.174153845725
0.834830769145
0.66276225436
0.932552450872
0.662356498023
0.932471299605
0.180297248133
0.836059449627
0.836059449627
0.967211889925
0.331547324556
0.866309464911
0.831657086315
0.966331417263
0.338120248569
0.867624049714
0.832919087725
0.966583817545
0.649669169753
0.929933833951
0.929933833951
0.98598676679
0.98598676679
0.997197353358
0.957309459224
0.991461891845
0.991461891845
0.998292378369
0.998292378369
0.999658475674
0.167942615662
0.833588523132
0.135715020722


In [10]:

print "Score over time: " +  str(sum(rList)/num_episodes)

SyntaxError: invalid syntax (<ipython-input-10-15b514b92e6a>, line 2)

In [11]:

#print "Final Q-Table Values"
print(Q)

[[  7.58235745e-02   4.98328319e-03   4.22165378e-03   5.28650149e-03]
 [  7.23362361e-04   2.08055854e-04   5.65367305e-04   2.13228348e-01]
 [  8.96080051e-04   8.75931114e-04   2.07137660e-03   2.06824944e-01]
 [  2.85940004e-04   4.42869092e-04   1.14053497e-04   6.16610378e-02]
 [  1.13992760e-01   1.48487314e-04   4.75144560e-04   5.57816703e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.73228800e-05   1.63094305e-04   1.07728435e-01   2.97188805e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.66511716e-04   6.61527616e-04   5.93640382e-04   1.28699206e-01]
 [  5.76526066e-04   2.71253193e-01   4.24688567e-03   0.00000000e+00]
 [  5.96411963e-01   4.70339494e-04   1.07469998e-03   6.22525568e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   5.37780394e-04   3.86186798e-01   4.97113622e-03]
 [  0.

In [13]:
print(Q)

[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.81450625  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.3773536   0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [16]:
print(Q)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  0.]]


In [18]:
print(Q)

[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.63024941  0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [20]:
print(Q)

[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.857375    0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.73509189  0.        ]
 [ 0.          0.          0.          0.        ]]


In [26]:
print(Q)

[[ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.857375]
 [ 0.        0.        1.        0.      ]
 [ 0.        0.        0.        0.      ]]


In [30]:
print(Q)

[[-0.22593554 -0.63024941 -0.56880009  0.        ]
 [-1.         -1.         -1.          0.        ]
 [-0.95       -0.95       -0.95        0.        ]
 [-1.         -1.         -1.          0.        ]
 [ 0.         -1.         -1.         -1.        ]
 [ 0.          0.          0.          0.        ]
 [-1.         -1.         -1.         -1.        ]
 [ 0.          0.          0.          0.        ]
 [-1.         -1.         -1.          0.857375  ]
 [-1.          0.81450625 -1.         -1.        ]
 [-0.95       -1.         -0.95       -1.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-1.         -1.          0.77378094 -1.        ]
 [ 0.          0.73509189  0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [32]:
print(Q)

[[-0.06983373 -0.06983373 -0.07737809  0.        ]
 [-0.1        -0.1        -0.1         0.        ]
 [-0.095      -0.095      -0.095       0.        ]
 [-0.1        -0.1        -0.1         0.        ]
 [-0.07737809 -0.07350919 -0.1        -0.1       ]
 [ 0.          0.          0.          0.        ]
 [-0.1        -0.1        -0.1        -0.1       ]
 [ 0.          0.          0.          0.        ]
 [-0.1        -0.1        -0.1        -0.07737809]
 [-0.1        -0.09025    -0.1        -0.1       ]
 [-0.0857375  -0.1        -0.095      -0.1       ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-0.1        -0.1         0.56880009 -0.1       ]
 [ 0.          0.          0.          1.        ]
 [ 0.          0.          0.          0.        ]]


In [34]:
env.observation_space.sample()

12

In [63]:
print(Q)

[[  5.96833411e-05   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.06357426e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.12948261e-04]
 [  0.00000000e+00   1.28484041e-05   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   8.40779757e-04   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.76314775e-03   0.00000000e+00]
 [  0.00000000e+00   2.30849287e-02   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.96768634e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.59668074e-01]
 [  0.

In [68]:
print(Q)

[[ 0.30399613  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.07999895  0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.13677106  0.          0.        ]
 [ 0.          0.70225335  0.          0.        ]
 [ 0.          0.65324879  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.18267694  0.          0.        ]
 [ 0.          0.          0.93375205  0.        ]
 [ 0.          0.          0.          0.        ]]


In [66]:
np.sum(rList)

188.0

In [41]:
np.argmax(ern)

0

In [42]:
np.max(ern)

0

In [44]:
np.random.choice(np.argwhere(ern == np.amax(ern)).flatten().tolist())

[0, 1, 2, 3]

In [48]:
np.random.choice([1,2,3,4])

1

In [49]:
ern

[0, 0, 0, 0]

In [50]:
np.argwhere(ern == np.max(ern)).flatten().tolist()

[0, 1, 2, 3]

In [51]:
np.max(ern)

0

In [56]:
np.random.choice(np.argwhere(ern == np.max(ern)).flatten())

1

In [61]:
np.sum(rList)

0