In [1]:
import numpy as np

In [2]:
next_states = {0:[0,1,4], 1:[0,1,2,5], 2:[1,2,3,6], 3:[2,3,7], 4:[0,4,5,8], 5:[5], 6:[2,5,7,10], 7:[7], 8:[4,8,9,12], 
               9:[5,8,10,13], 10:[6,9,11,14], 11:[11], 12:[12], 13:[9,12,13,14], 14:[10,13,14,15], 15:[5,7,11,12]}

In [3]:
trans_prob = np.zeros((16,16))

In [4]:
for i in next_states:
    pos = next_states[i]
    for j in pos:
        trans_prob[i,j] = 1

In [5]:
row_sums = trans_prob.sum(axis = 1)

In [6]:
trans_prob = trans_prob / row_sums[:, np.newaxis]

In [7]:
trans_prob

array([[ 0.33333333,  0.33333333,  0.        ,  0.        ,  0.33333333,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.25      ,  0.25      ,  0.25      ,  0.        ,  0.        ,
         0.25      ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.25      ,  0.25      ,  0.25      ,  0.        ,
         0.        ,  0.25      ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.        ,
         0.        ,  0.        ,  0.33333333,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.25      ,  0.        ,  0

In [8]:
r = np.zeros((16,1))

In [9]:
r[15] = 1

In [10]:
r

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.]])

In [11]:
v = np.zeros((16,1))

In [12]:
gamma = 0.95

In [13]:
v

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [14]:
v = r + gamma * np.matmul(trans_prob, v)

In [15]:
v

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.]])

In [16]:
v.shape

(16L, 1L)

In [17]:
v = np.zeros((16,1))

In [18]:
count = 0
while True:
    count += 1
    v_old = v[:]
    v = r + gamma * np.matmul(trans_prob, v)
    diff = np.sum(abs(v_old - v))
    if diff < 1e-10:
        break
print count

79


In [19]:
v

array([[ 0.0076612 ],
       [ 0.00664666],
       [ 0.01367806],
       [ 0.00633862],
       [ 0.0098854 ],
       [ 0.        ],
       [ 0.03092852],
       [ 0.        ],
       [ 0.02407615],
       [ 0.06741172],
       [ 0.11654727],
       [ 0.        ],
       [ 0.        ],
       [ 0.1432154 ],
       [ 0.39238509],
       [ 1.        ]])

In [20]:
v = r + gamma * np.matmul(trans_prob, v)

In [21]:
v

array([[ 0.0076612 ],
       [ 0.00664666],
       [ 0.01367806],
       [ 0.00633862],
       [ 0.0098854 ],
       [ 0.        ],
       [ 0.03092852],
       [ 0.        ],
       [ 0.02407615],
       [ 0.06741172],
       [ 0.11654727],
       [ 0.        ],
       [ 0.        ],
       [ 0.1432154 ],
       [ 0.39238509],
       [ 1.        ]])

In [22]:
v = np.zeros((16,1))

In [23]:
v = np.matmul(np.linalg.inv(1 - gamma * trans_prob), r) 

In [24]:
v

array([[ -6.72697140e+16],
       [  7.68454740e+16],
       [  4.78788000e+15],
       [  4.78788000e+15],
       [  4.78788000e+15],
       [  4.78788000e+15],
       [ -6.72697140e+16],
       [  4.78788000e+15],
       [  7.68454740e+16],
       [ -6.72697140e+16],
       [  4.78788000e+15],
       [  4.78788000e+15],
       [  4.78788000e+15],
       [ -6.72697140e+16],
       [  1.48903068e+17],
       [ -6.72697140e+16]])

In [25]:
np.linalg.inv(1 - gamma * trans_prob)

array([[ -1.49860115e+00,  -1.33226763e-15,   2.34341668e+00,
         -1.98994579e+00,   1.86710963e+00,   1.68174285e+16,
          0.00000000e+00,   1.68174285e+16,   4.21052632e+00,
         -7.53395116e-01,  -1.40852130e+00,   1.68174285e+16,
          1.68174285e+16,   8.88178420e-16,   2.24514775e+00,
         -6.72697140e+16],
       [ -1.44596958e+00,  -4.21052632e+00,   2.13289037e+00,
         -8.84682637e-01,   2.07763595e+00,  -1.92113685e+16,
          4.21052632e+00,  -1.92113685e+16,  -4.21052632e+00,
         -3.34988634e+00,  -2.60150376e+00,  -1.92113685e+16,
         -1.92113685e+16,   4.21052632e+00,  -1.96537856e+00,
          7.68454740e+16],
       [  3.26455674e+00,   2.05401112e-15,  -4.07763595e+00,
          3.29952789e+00,  -4.34341668e+00,  -1.19697000e+15,
         -4.21052632e+00,  -1.19697000e+15,  -5.45156123e-16,
          4.26414874e+00,   4.31077694e+00,  -1.19697000e+15,
         -1.19697000e+15,  -4.21052632e+00,   1.39884595e-01,
          4.7878

In [26]:
r

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.]])

In [27]:
trans_prob[15,15] = 1

In [28]:
v = np.zeros((16,1))

In [29]:
v = r + gamma * np.matmul(trans_prob, v)

In [30]:
v

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.]])

In [31]:
count = 0
while count < 1000:
    count += 1
    v_old = v[:]
    v = r + gamma * np.matmul(trans_prob, v)
    diff = np.sum(abs(v_old - v))
    if diff < 1e-10:
        break
print count

463


In [32]:
v

array([[  0.15322398],
       [  0.13293312],
       [  0.2735613 ],
       [  0.12677231],
       [  0.1977081 ],
       [  0.        ],
       [  0.61857032],
       [  0.        ],
       [  0.48152307],
       [  1.34823439],
       [  2.33094531],
       [  0.        ],
       [  0.        ],
       [  2.86430801],
       [  7.84770185],
       [ 20.        ]])

In [33]:
v = r + gamma * np.matmul(trans_prob, v)

In [34]:
v

array([[  0.15322398],
       [  0.13293312],
       [  0.2735613 ],
       [  0.12677231],
       [  0.1977081 ],
       [  0.        ],
       [  0.61857032],
       [  0.        ],
       [  0.48152307],
       [  1.34823439],
       [  2.33094531],
       [  0.        ],
       [  0.        ],
       [  2.86430801],
       [  7.84770185],
       [ 20.        ]])

In [35]:
v = np.matmul(np.linalg.inv(1 - gamma * trans_prob), r) 

In [36]:
v

array([[-1.05263158],
       [ 1.20247237],
       [ 0.0749204 ],
       [ 0.0749204 ],
       [ 0.0749204 ],
       [ 0.0749204 ],
       [-1.05263158],
       [ 0.0749204 ],
       [ 1.20247237],
       [-1.05263158],
       [ 0.0749204 ],
       [ 0.0749204 ],
       [ 0.0749204 ],
       [-1.05263158],
       [ 2.33002435],
       [-1.05263158]])

In [37]:
1 - gamma * trans_prob

array([[ 0.68333333,  0.68333333,  1.        ,  1.        ,  0.68333333,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ],
       [ 0.7625    ,  0.7625    ,  0.7625    ,  1.        ,  1.        ,
         0.7625    ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ],
       [ 1.        ,  0.7625    ,  0.7625    ,  0.7625    ,  1.        ,
         1.        ,  0.7625    ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ],
       [ 1.        ,  1.        ,  0.68333333,  0.68333333,  1.        ,
         1.        ,  1.        ,  0.68333333,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ],
       [ 0.7625    ,  1.        ,  1

In [38]:
np.linalg.inv(1 - gamma * trans_prob)

array([[ -3.15789474e+00,   0.00000000e+00,   4.21052632e+00,
         -3.15789474e+00,   0.00000000e+00,   1.31578947e+00,
          0.00000000e+00,   1.31578947e+00,   4.21052632e+00,
         -4.21052632e+00,  -4.21052632e+00,   1.31578947e+00,
         -7.89473684e-01,   8.88178420e-16,   4.21052632e+00,
         -1.05263158e+00],
       [  4.49522382e-01,  -4.21052632e+00,   1.59136111e-15,
          4.49522382e-01,   4.21052632e+00,  -1.35324967e+00,
          4.21052632e+00,  -1.35324967e+00,  -4.21052632e+00,
          5.99363177e-01,   5.99363177e-01,  -3.00618093e-01,
         -1.50777299e-01,   4.21052632e+00,  -4.21052632e+00,
          1.20247237e+00],
       [  3.38265593e+00,  -1.71752443e-15,  -4.21052632e+00,
          3.38265593e+00,  -4.21052632e+00,   1.03390148e+00,
         -4.21052632e+00,  -1.87300993e-02,   5.73599238e-16,
          4.51020790e+00,   4.51020790e+00,  -1.07136168e+00,
          1.10882188e+00,  -4.21052632e+00,  -9.55478324e-17,
          7.4920

In [39]:
ern = np.random.randn(5,1)

In [40]:
ern

array([[-0.91806312],
       [ 1.9467137 ],
       [-0.09712169],
       [ 0.52347169],
       [-0.88783211]])

In [41]:
kum = np.random.randn(5,5)

In [42]:
kum

array([[ 2.56410703,  0.23467881, -0.20679637,  0.23476261,  0.72733781],
       [ 0.02815628, -1.05933529,  1.18945385, -0.91716802,  1.50647748],
       [ 0.44060492,  1.17477659, -1.15851886,  0.25309864,  1.12514873],
       [-1.49825438,  1.16012565,  0.98124985,  0.48395934,  0.83937327],
       [-0.15150319, -0.20703166,  1.12469293, -0.66987916,  0.07142882]])

In [43]:
res_a = ern - np.matmul(kum, ern)

In [44]:
res_b = np.matmul((1-kum), ern)

In [45]:
res_a

array([[ 1.4818744 ],
       [ 5.9679178 ],
       [-1.22563636],
       [-2.52326873],
       [-0.10057858]])

In [46]:
res_b

array([[ 2.96710598],
       [ 4.58837257],
       [-0.5613462 ],
       [-2.47957195],
       [ 1.35442199]])

# Q Table Learning

In [47]:
Q = np.zeros((16,4))

In [48]:
Q

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [49]:
r = np.zeros((16,4))

In [50]:
r[14,2] = 1

In [51]:
r

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [52]:
max_q = np.max(Q, axis = 1)

In [53]:
max_q

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [54]:
p = np.array([[0,4,1,0], [0,5,2,1], [1,6,3,2], [2,7,3,3], [4,8,5,0], [5,5,5,5], [5,10,7,2], [7,7,7,7], [8,12,9,4], 
              [8,13,10,5], [9,14,11,6], [11,11,11,11], [12,12,12,12], [12,13,14,9], [13,14,15,10], [5,7,11,12]])

In [55]:
p

array([[ 0,  4,  1,  0],
       [ 0,  5,  2,  1],
       [ 1,  6,  3,  2],
       [ 2,  7,  3,  3],
       [ 4,  8,  5,  0],
       [ 5,  5,  5,  5],
       [ 5, 10,  7,  2],
       [ 7,  7,  7,  7],
       [ 8, 12,  9,  4],
       [ 8, 13, 10,  5],
       [ 9, 14, 11,  6],
       [11, 11, 11, 11],
       [12, 12, 12, 12],
       [12, 13, 14,  9],
       [13, 14, 15, 10],
       [ 5,  7, 11, 12]])

In [62]:
Q = np.zeros((16,4))

In [82]:
max_q = np.max(Q, axis = 1)
temp1 = np.zeros((16,4))
for i in xrange(len(max_q)):
    temp1 += (p==i) * max_q[i]
Q = r + gamma * temp1

In [83]:
Q

array([[ 0.73509189,  0.77378094,  0.77378094,  0.73509189],
       [ 0.73509189,  0.        ,  0.81450625,  0.77378094],
       [ 0.77378094,  0.857375  ,  0.77378094,  0.81450625],
       [ 0.81450625,  0.        ,  0.77378094,  0.77378094],
       [ 0.77378094,  0.81450625,  0.        ,  0.73509189],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.9025    ,  0.        ,  0.81450625],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.81450625,  0.        ,  0.857375  ,  0.77378094],
       [ 0.81450625,  0.9025    ,  0.9025    ,  0.        ],
       [ 0.857375  ,  0.95      ,  0.        ,  0.857375  ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.9025    ,  0.95      ,  0.857375  ],
       [ 0.9025    ,  0.95      ,  1.        ,  0.9025    ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [229]:
count = 0
while True:
    count += 1
    Q_old = Q[:]
    max_q = np.max(Q, axis = 1)
    temp1 = np.zeros((16,4))
    for i in xrange(len(max_q)):
        temp1 += (p == i) * max_q[i]
    Q = r + gamma * temp1
    if np.sum(abs(Q_old - Q)) < 1e-10:
        break
print count

8


In [230]:
Q

array([[ 0.73509189,  0.77378094,  0.77378094,  0.73509189],
       [ 0.73509189,  0.        ,  0.81450625,  0.77378094],
       [ 0.77378094,  0.857375  ,  0.77378094,  0.81450625],
       [ 0.81450625,  0.        ,  0.77378094,  0.77378094],
       [ 0.77378094,  0.81450625,  0.        ,  0.73509189],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.9025    ,  0.        ,  0.81450625],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.81450625,  0.        ,  0.857375  ,  0.77378094],
       [ 0.81450625,  0.9025    ,  0.9025    ,  0.        ],
       [ 0.857375  ,  0.95      ,  0.        ,  0.857375  ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.9025    ,  0.95      ,  0.857375  ],
       [ 0.9025    ,  0.95      ,  1.        ,  0.9025    ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [231]:
gamma = 0.8

In [232]:
Q = np.zeros((16,4))

In [233]:
count = 0
while True:
    count += 1
    Q_old = Q[:]
    max_q = np.max(Q, axis = 1)
    temp1 = np.zeros((16,4))
    for i in xrange(len(max_q)):
        temp1 += (p == i) * max_q[i]
    Q = r + gamma * temp1
    if np.sum(abs(Q_old - Q)) < 1e-10:
        break
print count

8


In [234]:
Q

array([[ 0.262144,  0.32768 ,  0.32768 ,  0.262144],
       [ 0.262144,  0.      ,  0.4096  ,  0.32768 ],
       [ 0.32768 ,  0.512   ,  0.32768 ,  0.4096  ],
       [ 0.4096  ,  0.      ,  0.32768 ,  0.32768 ],
       [ 0.32768 ,  0.4096  ,  0.      ,  0.262144],
       [ 0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.64    ,  0.      ,  0.4096  ],
       [ 0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.4096  ,  0.      ,  0.512   ,  0.32768 ],
       [ 0.4096  ,  0.64    ,  0.64    ,  0.      ],
       [ 0.512   ,  0.8     ,  0.      ,  0.512   ],
       [ 0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  0.      ],
       [ 0.      ,  0.64    ,  0.8     ,  0.512   ],
       [ 0.64    ,  0.8     ,  1.      ,  0.64    ],
       [ 0.      ,  0.      ,  0.      ,  0.      ]])