# Numpy Experiment

In [2]:
import numpy as np

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8] , [3,4,5,7]]
arr2= np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 7]])

In [10]:
arr2.ndim # to understand the number of dimention

2

In [11]:
arr2.shape # to understand the sahpe of the matrix

(3L, 4L)

In [12]:
arr2.dtype #to understand the data type

dtype('int32')

In [13]:
np.zeros(10) # create set of ten zeros

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((3,8)) # for two dymentional array we need to put double bracket

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
np.empty((2,3,4)) #empty creates an array without initializing its values to any particular value

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange((2,3))

TypeError: arange: scalar arguments expected instead of a tuple.

In [ ]:
#### Array creation functions#####

# array -->Convert input data (list, tuple, array, or other sequence type) to an ndarray either by
 # inferring a dtype or explicitly specifying a dtype. Copies the input data by default.

#asarray -->Convert input to ndarray, but do not copy if the input is already an ndarray

#arange -->Like the built-in range but returns an ndarray instead of a list.

#ones, ones_like -->Produce an array of all 1’s with the given shape and dtype. ones_like takes another
 #array and produces a ones array of the same shape and dtype.

#zeros, zeros_like -->Like ones and ones_like but producing arrays of 0’s instead

# empty, empty_like -->Create new arrays by allocating new memory, but do not populate with any values like
   #ones and zeros
    
#eye, identity -->Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)    
    

In [32]:
arr3=np.ones(4)
arr3

array([ 1.,  1.,  1.,  1.])

In [33]:
np.ones_like(arr2) #ones_like takes another array and produces a ones array of the same shape and dtype same works for zeros_like and empty like

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
np.eye(4) #Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)   

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [36]:
np.eye(4,3) # we can change the shape of the same as well

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

# Data type for Array

In [39]:
arr1=np.array([3,6,9],dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [43]:
arr1.dtype


dtype('float64')

In [44]:
arr2.dtype

dtype('int32')

In [ ]:
"""
int8, uint8 i1, u1 Signed and unsigned 8-bit (1 byte) integer types
int16, uint16 i2, u2 Signed and unsigned 16-bit integer types
int32, uint32 i4, u4 Signed and unsigned 32-bit integer types
int64, uint64 i8, u8 Signed and unsigned 32-bit integer types
float16 f2 Half-precision floating point
float32 f4 or f Standard single-precision floating point. Compatible with C float
float64, float128 f8 or d Standard double-precision floating point. Compatible with C double
and Python float object"""

In [ ]:
"""float128 f16 or g Extended-precision floating point
complex64, complex128,
complex256
c8, c16,
c32
Complex numbers represented by two 32, 64, or 128 floats, respectively
bool--> ?--> Boolean type storing True and False values
object--> O--> Python object type
string_ -->S--> Fixed-length string type (1 byte per character). For example, to create
a string dtype with length 10, use 'S10'.
unicode_ --> U -->Fixed-length unicode type (number of bytes platform specific). Same
specification semantics as string_ (e.g. 'U10')."""

In [ ]:
# conversion of data type for ana array

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int32')

In [5]:
float_arr = arr.astype(np.float64) # converson of type using dataname.astype

In [6]:
float_arr.dtype

dtype('float64')

In [7]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [8]:
arr.astype(np.int32) # as the converson is float to int the desimal point vanished

array([ 3, -1, -2,  0, 12, 10])

In [11]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array(['1.25', '-9.6', '42'], 
      dtype='|S4')

In [12]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [14]:
arr.astype(np.string_) # converting integer to string ' ' comes up

array(['3.7', '-1.2', '-2.6', '0.5', '12.9', '10.1'], 
      dtype='|S32')

In [16]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([ 0.22 ,  0.27 ,  0.357,  0.38 ,  0.44 ,  0.5  ])

In [18]:
int_array.astype(calibers.dtype) # it is autometically taking the format of calibers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [25]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([93257922,        0, 46820208,        0, 61539752,        0,
       94824888,        0], dtype=uint32)

# Operations between Arrays and Scalars

In [ ]:
"""Arrays are important because they enable you to express batch operations on data
without writing any for loops. This is usually called vectorization. Any arithmetic operations
between equal-size arrays applies the operation elementwise:"""

In [26]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [27]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [28]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [30]:
arr*10

array([[ 10.,  20.,  30.],
       [ 40.,  50.,  60.]])

# Basic Indexing and Slicing

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[7]

7

In [5]:
arr[5:9]

array([5, 6, 7, 8])

In [35]:
arr[5:9]=111 # assigning specific term of array to a different value

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr_slice=arr[5:8]
arr_slice

array([5, 6, 7])

In [10]:
array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9]) 


NameError: name 'array' is not defined

In [12]:
arr_slice[:] = 64

In [13]:
arr_slice

array([64, 64, 64])

In [ ]:
arr

# Dealing with higher dimentional array

In [42]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [44]:
arr2d[0]

array([1, 2, 3])

In [45]:
 arr2d[0][2] # eliment wise selection from a multidimentioanl array

3

In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [47]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr3d[0][0][0]

1

In [49]:
old_values = arr3d[0].copy() # coppied the old values of the array in temp file

In [50]:
arr3d[0] = 42 # it will apply 42 to all the items under arr3d[0]

In [51]:
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [52]:
arr3d[0]= old_values

In [53]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])